services:
  - type: web
    name: hpylori-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_URL
        value: https://your-app.netlify.app
      - key: SECRET_KEY
        value: 535153b8cb28a2967190a1d360122d8d24cb300555c69a6436a976d00e848232
    plan: free
    autoDeploy: true